### ISSUE TITLE
Add pin processing to symbols

### ISSUE THREAD

**Issue by shamilsan** [qeda/qeda-cli#5]
Need to add the pin processing for non-IC symbols.

Each pin in SVG should have the following ID: `pin-NET:halign:valign`.

`NET` may be pointed in the YAML description. For simple cases, there are default values.

```yaml
pinout:
  L: 1, 2 # If not specified, L=1 for capacitor
  R: 3, 4 # If not specified, R=2 for capacitor

symbol:
  type: capacitor
```

`halign` may be `left`, `center` or `right`.

`valign` may be `bottom`, `middle` or `top`.

When we have a single horizontal pin, we use `halign` only (`left` or `right`). Also, for single vertical pin `valign` is used (`bottom` or `top`).

`valign` is needed for horizontal pins when multiple pins are used. `halign` is required when we have multiple vertical pins.

See the picture below. But I am not sure about left/right and top/bottom directions, maybe they are needed to be vice versa (as with the text alignment). 

![image](https://user-images.githubusercontent.com/66209982/87534542-d5a95c00-c69e-11ea-8f2d-c73117b98d2b.png)
